### ISSUE TITLE
Project Proposal Feedback

### ISSUE THREAD

**Issue by natec425** [BaseCampCoding/fundamentals-of-programming-pt-1-unit-project-andy-and-dylan#1]
Hey @DylanMcC3525 and @andyduarte47,

Your project proposal looks good, but you didn't include a section for daily goals. Once you add this section, I think you'll be good to go.

**Comment by DylanMcC3525** [comment]
Ah, I see, ill make sure we get that done. Thanks!

**Comment by natec425** [comment]
The changes you made look good. I think you're ready to go ahead.

One note, be prepared to defend why your project is not _just_ a thin wrapper around Google translate. I think this project is giving you good practice interacting with an external API, but you need to make sure that it contains enough logic to stand on its own.

**Comment by DylanMcC3525** [comment]
Gotcha will do.

**Comment by andyduarte47** [comment]
Tuesday we will be going over the documentation for the module googletrans.
We will start a base for user input asking if they would want to read from
a file or not. Then ask the user for the language they want it translated
to and if they want it translated to multiple languages.
